Created retrieving CPU and RAM usage data using
yasha-nev/usage pull request #1
Opened 2023-10-03 16:17 UTC by yasha-nev

Прошу ревью на этот кусок недокода

2023-10-05 17:54 UTC, Crocussys commented on README.md
> +
Лишняя пустая строка. Мелочь, а глаз режет.

2023-10-05 17:57 UTC, yasha-nev commented on README.md
> +
Серьезно? Из всего этого ужаса. Ну если это важно для восприятия, то конечно. Сейчас поправлю

2023-10-05 17:59 UTC, yasha-nev commented on README.md
> +
Поправил

2023-10-05 17:59 UTC, Crocussys commented on README.md
> +
Хахахах. Ну я ещё не собирал. Тут надо смотреть, разбираться

2023-10-05 18:02 UTC, yasha-nev commented on README.md
> +
Тут кстати проблема, ты не соберешь. Работает только на операционках где ядром системы для управления всякими процессами является XNU Mach

2023-10-05 18:03 UTC, yasha-nev commented on README.md
> +
Я хотел сделать кроссплатформу, но ноут на линукса тавось. А VirtualBox в бете и почему то у меня не работает

2023-10-05 18:25 UTC, Crocussys commented
Ну да. Получаю ошибку
`$ make
[ 16%] Building CXX object CMakeFiles/usage.dir/src/CSVWrite.cpp.o
c++: error: unrecognized command-line option ‘-stdlib=libc++’
`
Система:
5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

2023-10-05 18:56 UTC, yasha-nev commented
Ааа, прости. Это надо уточнить было. Надо собирать не на gcc, а на clang компиляторе

2023-10-05 19:45 UTC, Crocussys commented
Ну. У меня только gcc есть. Как это собирать, я не знаю 🙃

2023-10-20 08:38 UTC, arybin93 requested changes
В целом, выглядит хорошо на сколько я могу понять))
Давно уже с плюсами не работал, но по логике вроде верно.

Основное замечание наверное, по использованию, я там в комментарии отписал, для пользователя интерфейс должен быть один, это запустить сборщик, ну может ещё выбрать метрику, как часто собирать и куда, как часто сохранять результаты. А всё остальное под капотом (cleanup, start, stop, get)

Можешь прицепить скриншот выполнения ещё?

2023-10-20 08:38 UTC, arybin93 commented on README.md
> +# ***APPLE Mac os CPU/RAM USAGE using mach***
Жаль, что только на маке)

2023-10-20 08:38 UTC, arybin93 commented on README.md
> +## function
Это всё должно быть внутри, для пользователя важно, просто запустить сборщик, ну ещё выключить, если не нужен. Хотя можно просто сигнал на kill отправить.

2023-10-20 08:38 UTC, arybin93 commented on README.md
> +## using
Можно добавить описание что делает программа, какие метрики собирает

2023-10-21 16:51 UTC, yasha-nev commented
Прикрепляю скриншоты. В целом вроде похоже на правду
![Uploading Снимок экрана 2023-10-21 в 19.43.44.png…]()
<img width="674" alt="Снимок экрана 2023-10-21 в 19 43 29" src="https://github.com/yasha-nev/usage/assets/79207709/22fc111a-1cbb-430f-b679-fcf125fe5573">
<img width="612" alt="Снимок экрана 2023-10-21 в 19 43 21" src="https://github.com/yasha-nev/usage/assets/79207709/433ab42b-66f3-4c6c-8742-f7ac1b38f1f2">

2023-10-21 16:52 UTC, yasha-nev commented
<img width="674" alt="Снимок экрана 2023-10-21 в 19 43 29" src="https://github.com/yasha-nev/usage/assets/79207709/645c46de-7cae-4683-9a17-86fb1a2c9ff2">

2023-10-21 16:56 UTC, yasha-nev commented on README.md
> +# ***APPLE Mac os CPU/RAM USAGE using mach***
Я хотел еще для линукса сделать, но виртуалка работать не хочет, да и мучится с #ifdef не хочется, станет еще менее читаемо

2023-10-25 18:06 UTC, arybin93 approved these changes
Отлично, можно мёржить)

2023-10-25 18:10 UTC, merged